Skip lint error stacktrace in Android lint smoke test
### Context

Since AGP 9.0.1, we saw such a stacktrace in Android lint smoke test:

```
Couldn't compute fix edits for null
java.lang.StringIndexOutOfBoundsException: begin 131, end 143, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
        ....
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Ignoring the stacktrace doesn't affect the test result.

Co-authored-by: Bo Zhang <bo@gradle.com>